"""added email to farmer

Revision ID: 3f63dfb5ea42
Revises: 1b70faad1931
Create Date: 2025-04-07 10:48:21.372106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f63dfb5ea42'
down_revision: Union[str, None] = '1b70faad1931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('email', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'farmers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farmers', type_='unique')
    op.drop_column('farmers', 'email')
    # ### end Alembic commands ###
