"""added mpesa no to farmer

Revision ID: a36584d62f0c
Revises: 3f63dfb5ea42
Create Date: 2025-04-07 11:02:41.398245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36584d62f0c'
down_revision: Union[str, None] = '3f63dfb5ea42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('mpesa', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmers', 'mpesa')
    # ### end Alembic commands ###
